global:
  scrape_interval: 10s # How often to scrape targets

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100','localhost:9090'] # The endpoint where your Node.js app is running
  - job_name: 'shoehub'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']
